title: "dch个人空间"
description: "A video codecer who running to AGI"
url: "https://bitchenhui.github.io"
baseurl: ""
lang: "zh-CN"
timezone: "Asia/Shanghai"
permalink: /blog/:title/
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections: {}

navigation:
  - title: 首页
    url: /
  - title: 项目
    url: /projects/
  - title: 博客
    url: /blog/
  - title: 关于
    url: /about/

author:
  name: "dch"
  role: "主动拥抱AGI的视频编解码算法工程师"
  intro: "用AI重塑所有流程中；ACL努力康复中的篮球爱好者；北京探店"
  email: "dch950301@163.com"
  github: ""
  linkedin: ""
  resume_url: ""

skills:
  - llm的eoH算法自动迭代设计
  - 视频编解码算法优化(H265/H266/AV1/NVC)
  - vod/live/rtc场景qos/qoe优化

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts
  - docs
